### ISSUE TITLE
Everything but eslint related things needs to be a dependency (instead of dev)

### ISSUE THREAD

**Issue by kristenmills** [rit-sse/qdb-3.0#12]
Based on current deployment setups, we need things like gulp in production. 

This should change based on things that @7imbrook is doing but if you want this to deploy properly in the current setup, move everything but stuff related to linting to regular dependencies.

**Comment by 7imbrook** [comment]
Doesn't matter all that much, once I build the source I'll blow away node_modules and most of the filesystem. Just enough to host the file (using node stdlib).

**Comment by kristenmills** [comment]
I meant that in an ideal situation, gulp should be a dev dependency and your setup will allow for that.

**Comment by 7imbrook** [comment]
Why does it matter? We're not including qdb as a library, they might as well all be regular dependancies. No real need to make a distinction right?

**Comment by kristenmills** [comment]
It doesn't matter. All i'm saying is if we wanted to organize it later, we could. Not saying we have to. Right now the way @bbesmanoff has it set up will not work. That's the point of this issue. But I just casually made the comment that the way he has it said will work in your setup.

**Comment by 7imbrook** [comment]
ah ok

**Comment by kristenmills** [comment]
I fixed this a couple days ago
