### ISSUE TITLE
Linter is Broken

### ISSUE THREAD

**Issue by bbesmanoff** [rit-sse/qdb-3.0#9]
The linter times out on CircleCI and appears to hang locally.

**Comment by bbesmanoff** [comment]
I have poked a little bit into this issue.  It looks like `npm run lint` fails.  Running `npm run lint -- --debug` gives a little more info (it fails on the navbar).  However, running `eslint <path_to>/navbar.js` doesn't show any errors.  I'll investigate further a little later on

**Comment by kristenmills** [comment]
It's probably a version issue. I'm currently updating our eslint config to work with eslint v2. That might just fix this issue.
